Feature/seq add layer
Igor-Vladyka/leaflet.motion pull request #25
Opened 2021-09-17 15:39 UTC by Patabugen

In response to this issue: https://github.com/Igor-Vladyka/leaflet.motion/issues/16

I've refactored the Sequence group a little so we can call `addLayer()` to add an animation step in the sequence after initialisation.

I've also added an examples folder as a form of documentation but also so I could use it for testing/developing this feature.

This is very bare bones and ready for me to try out for my own use case. Please let me know if you find any bugs, missing features or anything that doesn't work as you expect.

There is one breaking change: I've changed `seq.motionStart()` to act the same way as `polyline.motionStart()` (to do nothing if the animation has started, instead of restarting the animation). It's not actually required for my new functionality.

```javascript
var trackPolyline = L.motion.polyline(trackRoute).motionDuration(2000);
var shipPolyline = L.motion.polyline(shipRoute).motionDuration(2000);
var carPolyline = L.motion.polyline(carRoute).motionDuration(2000);

// Build the Sequence Group:
var seqGroup = L.motion.seq([
    trackPolyline, shipPolyline
]).addTo(map);
            
seqGroup.addLayer(carPolyline);

```

2022-02-05 15:03 UTC, Igor-Vladyka commented
Overall it's a good idea and a valid approach, but need more in-deept modification to SEQ and to the root motion module.

Please resolve conflicts, and merge it into separate branch.

2022-02-05 15:03 UTC, Igor-Vladyka requested changes

2022-02-05 15:03 UTC, Igor-Vladyka commented on src/layer/leaflet.motion.seq.js
> +			l.motionStart();
If we created a SEQ with few layers, have not started it, and add one more layer on top of it, it will start running from this last layer.

2022-02-16 12:57 UTC, Igor-Vladyka commented
I've integrated part of your changes into the plugin, and part of documentation for it. Please check it out, and test it.

2022-02-16 12:57 UTC, closed without merging

2022-02-28 10:54 UTC, Patabugen commented
Thanks @Igor-Vladyka ! I'm hoping to spend some time on the project using this in the next month or two so will have a look!

GitHub is saying some commits aren't merged, but I'm not sure how to see which they are - do you know how to? (I'm mostly curious to see which ones).